# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ernst Luring
email: ernst_luring@hotmail.com
description: Game Development and Programming portfolio of Ernst Luring.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ernstluring.nl" # the base hostname & protocol for your site
twitter_username: ejluring
github_username:  ernstluring
linkedin_username: ernstluring

# Build settings
markdown: kramdown
