# Permalinks
permalink: pretty

# Setup
title: "EJL Digital"
url: https://ejldigital.com
# tagline: "Optimizing application performances, improving workflows and creating digital products"
tagline: "Improving workflows by creating tools and apps"

headline: "Hey, I’m Ernst!"
baseurl: ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
# sass:
#   sass_dir: _sass
#   style: :compressed

# About/contact
author:
  name: Ernst Luring
  twitter: https://twitter.com/ejldigital
  email: ernst@ejldigital.com
  linkedin: https://www.linkedin.com/in/ernstluring/
  github: https://github.com/ernstluring

collections:
  - latest_work
# Custom vars
version: 1.0.0
