# Permalinks
permalink: pretty

# Setup
title: "EJL Digital"
url: https://ejldigital.com
tagline: "I create games, apps and tools that are intuitive, fun and support
  people in their lives and work."

headline: "Hi, I’m Ernst"
baseurl: ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
# sass:
#   sass_dir: _sass
#   style: :compressed

# About/contact
author:
  name: Ernst Luring
  twitter: https://twitter.com/ejldigital
  email: ernst@ejldigital.com
  linkedin: https://www.linkedin.com/in/ernstluring/
  github: https://github.com/ernstluring
  instagram: https://www.instagram.com/ejldigital/
  kvk: 83625259

collections:
  - latest_work
# Custom vars
version: 1.0.0
